on: [push]

name: CI

jobs:
  build:
    name: Nvim Command Runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: upload target
          path: target

